baseURL = ""
languageCode = "en-us"
title = "Introduktion til Text Mining i Python"
themesDir = "themes"
theme = "hugo-theme-learn"
relativeurls = true

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
url = "https://github.com/CALDISS-AAU/workshop_python-text-mining"

